#
# router R3 MSNM configuration file
#

DataSources:
  calibrationFile: /home/nesg/git/VERITASExperimentalScripts/control/scripts/MSNMsensor/config/scenario_4/data/all_datasets.mat
  calibrationMatrix: XR3c
  calibrationVariables: var_R3
    
  local:
    Netflow:
      type: local
      # Module containing the local data source class
      moduleName: msnm.modules.source.netflow
      captures: /home/nesg/git/VERITASExperimentalScripts/machines/routers/capturas
      raw: ./data/sources/local/netflow/raw/
      processed: ./data/sources/local/netflow/processed/
      parsed: ./data/sources/local/netflow/parsed/
      flowParserConfig: config/netflow_parser.yaml
      flowParserContents: config/trevenque_netflow.yaml
      # Run manual (False) or automatic (True) nfcapd
      nfcapdAutomaticStart: False
      # Static mode where the *.dat files are manually provided in parsed folder
      staticMode: False
      # Path where the *.dat files can be found. These files are the results of the flow parser.
      staticParsedFilesPath: /home/roberto/RMAGAN/nesgownCloud/INVESTIGACION/PROYECTOS/Nacionales/VERITAS/DESARROLLO/SENSOR/dataset/metis/dataset_pepe/data_matlab/matlab_routerR3/
      # Static files range to build the data for testing. Date limits are included in the results.
      staticObsRangeStart: '2016-02-10 12:21'
      staticObsRangeEnd: '2016-02-10 13:51'    
      
Sensor:
  observation: ./data/monitoring/observation/
  output: ./data/monitoring/output/
  model: ./data/calibration/
  diagnosis: ./data/diagnosis/
  # Latent variables
  lv: 2
  # Data preprocessing method
  # 0: no preprocessing 
  # 1: mean-centering 
  # 2: auto-scaling
  prep: 2
  # Choose the phase to compute UCLd:           
  # 1: Phase I 
  # 2: Phase II
  phase: 1
  
  # Local unique sensor identifier
  sid: routerR3
  # EWMA dynamic calibration parameters
  dynamiCalibration:    
    # Batch of observations
    B: 30
    # Forgetting factor
    lambda: 0.1
    # enabled?
    enabled: False
  
  # Server configuration. To listen other sensors queries
  server_address: 
    ip: routerR3
    port: 9003
  # List of sensor to send data packets
  remote_addresses:
    borderRouter:
      ip: borderRouter
      port: 9005
      
GeneralParams:
  dateFormat: '%Y-%m-%d %H:%M:%S'
  dateFormatNfcapdFiles: '%Y%m%d%H%M'
  # Data format for timestamps
  tsDateFormat: '%Y%m%d%H%M'
  # Time interval in seconds to get data from local sources
  dataSourcesScheduling: 60
  # Polling time interval in seconds for polling data sources
  dataSourcesPolling: 1
  # Timeout in seconds to wait the other not ready data sources
  dataSourcesNotReadyWaitingTime: 5
  valuesFormat: '%1.5f'
  serverConnectionTimeout: 15
  
  
